Issue#4 refactoring scripts
vaimee/desmo-dapp pull request #10
Opened 2022-08-25 12:41 UTC by FerrariAndrea

Warn: this PR includes the fixes on the branch `issue#2_callbackhell`, this branch has already been merged with `issue#2_callbackhell`.

2022-08-30 17:07 UTC, hyperloris commented on .gitignore
> +Dapp/build
The correct name is `DApp`, with a capital A. Right now it is not ignoring the build folder.

2022-08-31 05:45 UTC, hyperloris commented on DApp/package.json
> +    "start":"node build/app.js \"0x000000000000000000000000000000000000000000000000000000000000000b\" \"{__!_prefixList__!_:[{__!_abbreviation__!_:__!_desmo__!_,__!_completeURI__!_:__!_https://desmo.
I think this script is a bit too verbose, could you move it to a dedicated file inside a `scripts` folder?
I also encountered a problem with its execution: `sh: line 1: ?(@[--#-type--#-]==--#-Sensor--#-): syntax error: operand expected (error token is "?(@[--#-type--#-]==--#-Sensor--#-)")`

2022-08-31 05:48 UTC, hyperloris commented on DApp/package.json
> +    "lint": "eslint . --ext .ts",
Add `eslint` to devDependencies.

2022-08-31 06:13 UTC, hyperloris commented on DApp/package.json
> +    "docker_build": "docker build . --tag desmo-dapp",
I suggest using another type of convention for script names: instead of the underscore, it would be preferable to use lowerCamelCase or a **colon delimiter** (more consistent with the other repositories).
Do this for the other scripts as well.

2022-08-31 06:14 UTC, hyperloris commented on DApp/package.json
> +    "docker_run": "docker run --rm -v %CD%/mount/iexec_in:/iexec_in -v %CD%/mount/iexec_out:/iexec_out -e IEXEC_IN=/iexec_in -e IEXEC_OUT=/iexec_out desmo-dapp \"0x00000000000000000000000000000000000
Same as the `start` script.

2022-08-31 06:25 UTC, hyperloris commented on DApp/src/app.ts
> +        const worker = new Worker("/iexec_out");
Put this into a **constant**. May I suggest to use the `const/Config.ts`?

2022-08-31 06:42 UTC, hyperloris commented on DApp/src/component/Worker.ts
>      }
I think you can simply use the env IEXEC_OUT: can be set even if you are not using Docker. Am I missing something?

2022-08-31 06:59 UTC, hyperloris commented on DApp/tsconfig.json
> +  "exclude": [
Why excluding these folders? I think this will create problems in the test files.

2022-08-31 07:15 UTC, hyperloris requested changes, later dismissed
Thanks for the contribution!
There are minor issues (mainly style) and some more significant, such as script execution failing. Take a look at it and let me know :wink:

2022-08-31 08:14 UTC, FerrariAndrea commented on DApp/package.json
> +    "start":"node build/app.js \"0x000000000000000000000000000000000000000000000000000000000000000b\" \"{__!_prefixList__!_:[{__!_abbreviation__!_:__!_desmo__!_,__!_completeURI__!_:__!_https://desmo.
@relu91 what do you think about moving these npm commands to external scripts? I understood that we should not use scripts, and prefer to use npm run calls.

About the error that you find, that is strange, on my environment it works perfectly:
```
$ npm start

> iexec@1.0.0 start
> node build/app.js "0x000000000000000000000000000000000000000000000000000000000000000b" "{__!_prefixList__!_:[{__!_abbreviation__!_:__!_desmo__!_,__!_completeURI__!_:__!_https://desmo.vaimee.it/__!_},{__!_abbreviation__!_:__!_qudt__!_,__!_completeURI__!_:__!_http://qudt.org/schema/qudt/__!_},{__!_abbreviation__!_:__!_xsd__!_,__!_completeURI__!_:__!_http://www.w3.org/2001/XMLSchema/__!_},{__!_abbreviation__!_:__!_monas__!_,__!_completeURI__!_:__!_https://pod.dasibreaker.vaimee.it/monas/__!_}],__!_property__!_:{__!_identifier__!_:__!_value__!_,__!_unit__!_:__!_qudt:DEG_C__!_,__!_datatype__!_:1},__!_staticFilter__!_:__!_$[?(@[--#-type--#-]==--#-Sensor--#-)]__!_}"

[Wed Aug 31 2022 10:12:59 GMT+0200 (Ora legale dell’Europa centrale)][APP]: DApp started!
[Wed Aug 31 2022 10:12:59 GMT+0200 (Ora legale dell’Europa centrale)][APP]: ["C:\\Program Files\\0_Programmazione\\nodejs\\node.exe","D:\\VAIMEE\\DESMOLD\\desmo-dapp\\DApp\\build\\app.js","0x000000000000000000000000000000000000000000000000000000000000000b","{__!_prefixList__!_:[{__!_abbreviation__!_:__!_desmo__!_,__!_completeURI__!_:__!_https://desmo.vaimee.it/__!_},{__!_abbreviation__!_:__!_qudt__!_,__!_completeURI__!_:__!_http://qudt.org/schema/qudt/__!_},{__!_abbreviation__!_:__!_xsd__!_,__!_completeURI__!_:__!_http://www.w3.org/2001/XMLSchema/__!_},{__!_abbreviation__!_:__!_monas__!_,__!_completeURI__!_:__!_https://pod.dasibreaker.vaimee.it/monas/__!_}],__!_property__!_:{__!_identifier__!_:__!_value__!_,__!_unit__!_:__!_qudt:DEG_C__!_,__!_datatype__!_:1},__!_staticFilter__!_:__!_$[?(@[--#-type--#-]==--#-Sensor--#-)]__!_}"]
[Wed Aug 31 2022 10:12:59 GMT+0200 (Ora legale dell’Europa centrale)][Worker]: QUERY is: {"prefixList":[{"abbreviation":"desmo","completeURI":"https://desmo.vaimee.it/"},{"abbreviation":"qudt","completeURI":"http://qudt.org/schema/qudt/"},{"abbreviation":"xsd","completeURI":"http://www.w3.org/2001/XMLSchema/"},{"abbreviation":"monas","completeURI":"https://pod.dasibreaker.vaimee.it/monas/"}],"property":{"identifier":"value","unit":"qudt:DEG_C","datatype":1},"staticFilter":"$[?(@['type']=='Sensor')]"}
[Wed Aug 31 2022 10:12:59 GMT+0200 (Ora legale dell’Europa centrale)][DesmoSDKWrapper]: Resolve requestID to retrieve TDDs. RequestiD: 0x000000000000000000000000000000000000000000000000000000000000000b
[Wed Aug 31 2022 10:13:01 GMT+0200 (Ora legale dell’Europa centrale)][DesmoSDKWrapper]: DEBUG: sanityzzeMap: ["https://desmold-zion-1.vaimee.it","https://desmold-zion-2.vaimee.it","https://desmold-zion-3.vaimee.it","https://desmold-zion-4.vaimee.it"]
[Wed Aug 31 2022 10:13:01 GMT+0200 (Ora legale dell’Europa centrale)][Worker]: Parsing query ...
[Wed Aug 31 2022 10:13:01 GMT+0200 (Ora legale dell’Europa centrale)][Worker]: Collect Directories and TDs ...
[Wed Aug 31 2022 10:13:01 GMT+0200 (Ora legale dell’Europa centrale)][DirectoriCollector]: request_path: https://desmold-zion-1.vaimee.it/search/jsonpath?query=%24%5B%3F(%40%5B'type'%5D%3D%3D'Sensor')%5D
[Wed Aug 31 2022 10:13:01 GMT+0200 (Ora legale dell’Europa centrale)][DirectoriCollector]: request_path: https://desmold-zion-2.vaimee.it/search/jsonpath?query=%24%5B%3F(%40%5B'type'%5D%3D%3D'Sensor')%5D
[Wed Aug 31 2022 10:13:01 GMT+0200 (Ora legale dell’Europa centrale)][DirectoriCollector]: request_path: https://desmold-zion-3.vaimee.it/search/jsonpath?query=%24%5B%3F(%40%5B'type'%5D%3D%3D'Sensor')%5D
[Wed Aug 31 2022 10:13:01 GMT+0200 (Ora legale dell’Europa centrale)][DirectoriCollector]: request_path: https://desmold-zion-4.vaimee.it/search/jsonpath?query=%24%5B%3F(%40%5B'type'%5D%3D%3D'Sensor')%5D
[Wed Aug 31 2022 10:13:01 GMT+0200 (Ora legale dell’Europa centrale)][DirectoriCollector]: Pre punished source: 0/4
[Wed Aug 31 2022 10:13:02 GMT+0200 (Ora legale dell’Europa centrale)][Worker]: Collect values ...
[Wed Aug 31 2022 10:13:02 GMT+0200 (Ora legale dell’Europa centrale)][Worker]: ###INFO###: Using NumberSourceValues.
[Wed Aug 31 2022 10:13:02 GMT+0200 (Ora legale dell’Europa centrale)][Worker]: ###: 6
[Wed Aug 31 2022 10:13:02 GMT+0200 (Ora legale dell’Europa centrale)][DataCollector]: collect started!
[Wed Aug 31 2022 10:13:02 GMT+0200 (Ora legale dell’Europa centrale)][WotSource]: Ask for a value, response: 60.18
[Wed Aug 31 2022 10:13:02 GMT+0200 (Ora legale dell’Europa centrale)][WotSource]: Ask for a value, response: 16.61
[Wed Aug 31 2022 10:13:02 GMT+0200 (Ora legale dell’Europa centrale)][WotSource]: Ask for a value, response: 176.93
[Wed Aug 31 2022 10:13:02 GMT+0200 (Ora legale dell’Europa centrale)][WotSource]: Ask for a value, response: 28.54
[Wed Aug 31 2022 10:13:02 GMT+0200 (Ora legale dell’Europa centrale)][WotSource]: Ask for a value, response: 59.03
[Wed Aug 31 2022 10:13:02 GMT+0200 (Ora legale dell’Europa centrale)][WotSource]: Ask for a value, response: 53.41
[Wed Aug 31 2022 10:13:02 GMT+0200 (Ora legale dell’Europa centrale)][WotSource]: Ask for a value, response: 87.85
[Wed Aug 31 2022 10:13:02 GMT+0200 (Ora legale dell’Europa centrale)][WotSource]: Ask for a value, response: 35.27
[Wed Aug 31 2022 10:13:02 GMT+0200 (Ora legale dell’Europa centrale)][WotSource]: Ask for a value, response: 84.67
[Wed Aug 31 2022 10:13:02 GMT+0200 (Ora legale dell’Europa centrale)][WotSource]: Ask for a value, response: 19.73
[Wed Aug 31 2022 10:13:02 GMT+0200 (Ora legale dell’Europa centrale)][WotSource]: Ask for a value, response: 181.76
[Wed Aug 31 2022 10:13:02 GMT+0200 (Ora legale dell’Europa centrale)][WotSource]: Ask for a value, response: 109.78
[Wed Aug 31 2022 10:13:02 GMT+0200 (Ora legale dell’Europa centrale)][WotSource]: Ask for a value, response: 13.13
[Wed Aug 31 2022 10:13:02 GMT+0200 (Ora legale dell’Europa centrale)][WotSource]: Ask for a value, response: 85.14
[Wed Aug 31 2022 10:13:02 GMT+0200 (Ora legale dell’Europa centrale)][WotSource]: Ask for a value, response: 39.8
[Wed Aug 31 2022 10:13:02 GMT+0200 (Ora legale dell’Europa centrale)][WotSource]: Ask for a value, response: 81.6
[Wed Aug 31 2022 10:13:02 GMT+0200 (Ora legale dell’Europa centrale)][WotSource]: Ask for a value, response: 3.13
[Wed Aug 31 2022 10:13:02 GMT+0200 (Ora legale dell’Europa centrale)][WotSource]: Ask for a value, response: 48.69
[Wed Aug 31 2022 10:13:02 GMT+0200 (Ora legale dell’Europa centrale)][WotSource]: Ask for a value, response: 77.35
[Wed Aug 31 2022 10:13:02 GMT+0200 (Ora legale dell’Europa centrale)][WotSource]: Ask for a value, response: 8.34
[Wed Aug 31 2022 10:13:02 GMT+0200 (Ora legale dell’Europa centrale)][WotSource]: Ask for a value, response: 12.96
[Wed Aug 31 2022 10:13:02 GMT+0200 (Ora legale dell’Europa centrale)][WotSource]: Ask for a value, response: 29.83
[Wed Aug 31 2022 10:13:02 GMT+0200 (Ora legale dell’Europa centrale)][WotSource]: Ask for a value, response: 106.06
[Wed Aug 31 2022 10:13:02 GMT+0200 (Ora legale dell’Europa centrale)][WotSource]: Ask for a value, response: 100.59
[Wed Aug 31 2022 10:13:02 GMT+0200 (Ora legale dell’Europa centrale)][ConsensusForNumber]: Using consensus alghoritm for NUMBER
[Wed Aug 31 2022 10:13:02 GMT+0200 (Ora legale dell’Europa centrale)][ConsensusForNumber]: X[0]bestSource[1]
[Wed Aug 31 2022 10:13:02 GMT+0200 (Ora legale dell’Europa centrale)][ConsensusForNumber]: X[1]bestSource[1]
[Wed Aug 31 2022 10:13:02 GMT+0200 (Ora legale dell’Europa centrale)][ConsensusForNumber]: X[2]bestSource[1]
[Wed Aug 31 2022 10:13:02 GMT+0200 (Ora legale dell’Europa centrale)][ConsensusForNumber]: X[3]bestSource[1]
[Wed Aug 31 2022 10:13:02 GMT+0200 (Ora legale dell’Europa centrale)][ConsensusForNumber]: X[4]bestSource[1]
[Wed Aug 31 2022 10:13:02 GMT+0200 (Ora legale dell’Europa centrale)][ConsensusForNumber]: X[5]bestSource[1]
[Wed Aug 31 2022 10:13:02 GMT+0200 (Ora legale dell’Europa centrale)][Wor [...]

2022-08-31 08:24 UTC, FerrariAndrea commented on DApp/src/component/Worker.ts
>      }
good point, the problem is that the `defualtPathOut ` can be not set and `process.env.IEXEC_OUT ` can be not setted as well, but one of the two must be set. So if both are undefined I'm setting ` this.iexecOut = "";` and then I check it later in order to exit with an exception.

I can remove skip that step and exit with the exception directly instead of ` this.iexecOut = "";`. But I prefer not to exit inside the constructor. (you can see this check at lines 64-66 of Worker.ts)

What do you think?

2022-08-31 08:28 UTC, FerrariAndrea commented on DApp/tsconfig.json
> +  "exclude": [
I exclude `support` and `tests` folders from the build, because in the Docker image I don't need them.
The test folder contains Jest test and currently, I run it without pre-build the code, `cd ./tests && npx jest`.
Jest seems not to need the build files.

2022-09-05 09:53 UTC, relu91 commented on DApp/package.json
> +    "start":"node build/app.js \"0x000000000000000000000000000000000000000000000000000000000000000b\" \"{__!_prefixList__!_:[{__!_abbreviation__!_:__!_desmo__!_,__!_completeURI__!_:__!_https://desmo.
For now, it's ok to have a long script. In the future we might consider:
1. Using default arguments
2. Use external sh scripts
3. Use configuration files. 

One thing that we need to solve now is the issue with linux cmd. The same npm script should work both for windows and linux.

2022-09-05 09:56 UTC, hyperloris commented on DApp/src/component/Worker.ts
>      }
I suggest removing this code from the constructor. Read the env from outside (app.ts) and pass the value when you instantiate the `Worker`.

2022-09-05 10:00 UTC, hyperloris commented on DApp/tsconfig.json
> +  "exclude": [
Do not remove these folders from `tsconfig`. If you want to exclude them from the Docker image, then use a [.dockerignore](https://docs.docker.com/engine/reference/builder/#dockerignore-file) file.

2022-09-05 18:07 UTC, FerrariAndrea commented on DApp/package.json
> +    "start":"node build/app.js \"0x000000000000000000000000000000000000000000000000000000000000000b\" \"{__!_prefixList__!_:[{__!_abbreviation__!_:__!_desmo__!_,__!_completeURI__!_:__!_https://desmo.
OKs, I do some changes, look at the new push, I move the 2 long npm commands to external scripts, I think that should work on Windows and Linux, pls test it, because in my Ubuntu the previous version was working already.

2022-09-05 18:08 UTC, FerrariAndrea commented on DApp/tsconfig.json
> +  "exclude": [
ok, I will do that in PR #13, if it is ok for you

2022-09-05 18:10 UTC, FerrariAndrea commented on DApp/src/component/Worker.ts
>      }
Oks, I will do it in PR #13, if it is ok for you.

2022-09-06 09:21 UTC, hyperloris commented on DApp/src/component/Worker.ts
>      }
Please make changes in this PR. #13 is about testing and I prefer not to mix the two.

2022-09-06 09:21 UTC, hyperloris commented on DApp/tsconfig.json
> +  "exclude": [
Please make changes in this PR. #13 is about testing and I prefer not to mix the two.

2022-09-06 09:52 UTC, relu91 commented on DApp/package.json
> +    "start":"node build/app.js \"0x000000000000000000000000000000000000000000000000000000000000000b\" \"{__!_prefixList__!_:[{__!_abbreviation__!_:__!_desmo__!_,__!_completeURI__!_:__!_https://desmo.
![image](https://user-images.githubusercontent.com/3170227/188604759-f294b44c-b56d-4ce0-bf77-9be7b0d2459e.png)

When I said **in the future** I meant **not in this PR**. 😄

2022-09-06 13:03 UTC, FerrariAndrea commented on DApp/package.json
> +    "start":"node build/app.js \"0x000000000000000000000000000000000000000000000000000000000000000b\" \"{__!_prefixList__!_:[{__!_abbreviation__!_:__!_desmo__!_,__!_completeURI__!_:__!_https://desmo.
yea but I don't know how I can fix the quotes problem, this is the solution that I found!

2022-09-06 16:55 UTC, relu91 commented
@FerrariAndrea no worries about the scripts now. After my commit [6da6232](https://github.com/vaimee/desmo-dapp/pull/10/commits/6da623231deff1a2903667578d872e2fd5eaf5f5) the situation is better but it is still hard to make it work. Please finish what @hyperloris asked then I'll take over some points.

2022-09-06 16:55 UTC, relu91 commented
Also the start script depends on the resolution of #1 .

2022-09-07 08:59 UTC, FerrariAndrea commented on DApp/tsconfig.json
> +  "exclude": [
Done

2022-09-07 08:59 UTC, FerrariAndrea commented on DApp/src/component/Worker.ts
>      }
Done

2022-09-07 09:03 UTC, FerrariAndrea commented
Note, when that PR will be merged, remember to change the Dockerfile, I think the path of the application inside the Dokerfile will need an update.
Removing the "exclude" from "tsconfig.json" the path of the build files are changed, from `build/app.js` to `build/src/app.js`.

The Dockerfile that is in that PR is useless, and not updated to the Dockerfile PR #12.

2022-09-07 12:22 UTC, relu91 requested changes
Small thing and then we are ready to merge from my side. But also let's wait for @hyperloris green light.

2022-09-07 12:22 UTC, relu91 commented on DApp/src/app.ts
> +        var iexecOut= process.env.IEXEC_OUT;
use let instead of var.

2022-09-07 16:22 UTC, relu91 approved these changes
Ok we can move on 👍🏻

2022-09-07 16:23 UTC, merged