Not punish if no prop
vaimee/desmo-dapp pull request #17
Opened 2022-09-16 17:22 UTC by FerrariAndrea

change logic: if a TD has no prop, this will be discarded without punish.

in this PR there are some edit to the TD of WAM

That PR is useful if you want call a query with no static filter

2022-09-20 09:06 UTC, relu91 requested changes
See the comment below. Moreover, you mentioned in the PR description that these changes should help to issue a query without a `staticFilter`, can you point me to the code that handles that part?

2022-09-20 09:06 UTC, relu91 commented on DApp/src/component/DirectoriesCollector.ts
> +                    const reader = await thing.readAllProperties();
To check for a property's existence you can simply read its Thing Description. Calling reallAllProperties means sending a network request to the network. I don't think it is necessary.

2022-09-20 10:29 UTC, relu91 approved these changes
Looks good now, however you didn't answer my question.

2022-09-22 15:28 UTC, FerrariAndrea commented
> Looks good now, however you didn't answer my question.

as always I mis it your comment, I just saw the comment below...

2022-09-22 15:38 UTC, FerrariAndrea commented on DApp/src/component/DirectoriesCollector.ts
> +                    if(hasThatPros){
> See the comment below. Moreover, you mentioned in the PR description that these changes should help to issue a query without a `staticFilter`, can you point me to the code that handles that part?

It is the new logic itself that allows using a query without the `staticFilter`. 
I will try to explain better, without the check on the "hasThatProps" added by that PR, if we run a query without the `staticFilter`, all the TDs of any Directories used will be selected, and so the DApp will fail for "no consensus reached", because all the TDs will be used and more of them can't answer to our requests (because they do not have the specified props).

Adding the filter "hasThatProps" you can run a query without the `staticFilter`, because the TDs will be filtered (without being punished yet) anyway on the constraint of the requested props by the query.

Tell me if it is not clear.

2022-09-23 15:29 UTC, relu91 commented on DApp/src/component/DirectoriesCollector.ts
> +                    if(hasThatPros){
thanks! it makes totally sense :) merging 🥳

2022-09-23 15:30 UTC, merged