fix issue#2 callback hell
vaimee/desmo-dapp pull request #8
Opened 2022-08-23 15:50 UTC by FerrariAndrea

- Rework callback to promise (async/await) finished and tested.
- WARN: some fixes are due to resolve other issues
- Removed some useless files
- Jest coverage: 95.27%
- Jest test passed, still 1 test failed cause of Zion query parser

2022-08-24 07:53 UTC, relu91 requested changes
General note, try not to commit uncommented code, it is a bad practice. I did not review the tests one to one cause we probably need to change them when #7 is done.

2022-08-24 07:53 UTC, relu91 commented on DApp/src/component/DirectoriesCollector.ts
> +        return ris;
The refactored code does not contain any `await` call however it returns a Promise. What I also see is that `DirectoriesCollector` implements [IDirectoryCollettor](https://github.com/vaimee/desmo-dapp/blob/main/DApp/src/component/IDirectoriesCollector.ts) which is not updated in this PR. 

Questions:
1. Are you sure that you would need an asynchronous function for this functionality in `IDirectoryCollettor`
2. Double check that you don't have uncommitted changes

2022-08-24 07:53 UTC, relu91 commented on DApp/src/component/DirectoriesCollector.ts
> +                )
In this case you can even omit the `await` keyword

2022-08-24 07:53 UTC, relu91 commented on DApp/src/component/DirectoriesCollector.ts
> +        return ris;
I am not seeing any await call in this function too. Are you sure it needs to by async?

2022-08-24 07:53 UTC, relu91 commented on DApp/src/component/DirectoriesCollector.ts
> +        //cb: (resolvedSources: Map<string, Array<ISource>>) => void
Commented code -> bad thing.

2022-08-24 07:53 UTC, relu91 commented on DApp/src/component/Worker.ts
> +import QueryParser from "./QueryParser";
The folder [componet](https://github.com/vaimee/desmo-dapp/tree/main/DApp/src/component) does not contain a file called `QueryParser.ts`. Neither I am seeing a change to rename that file. ARE YOU **SURE** that you don't have uncommitted changes???

2022-08-24 07:53 UTC, relu91 commented on DApp/src/component/Worker.ts
> +            // try {
Remove this poor thing.

2022-08-24 07:53 UTC, relu91 commented on DApp/src/component/Worker.ts
> +              this.cb(computedJsonObj);
HELL 🔥 . Is this still needed where does it come from?

2022-08-24 07:53 UTC, relu91 commented on DApp/src/component/consensus/dataCollector.ts
> +    return await recursive();
Self reminder, discuss about this logic

2022-08-24 07:53 UTC, relu91 commented on DApp/src/component/queryParser.ts
> +var jp = require('jsonpath'); //import jp from "jsonpath"; DO NOT WORK :(
I saw that you added jsonpath types, is this still not working?

2022-08-25 13:51 UTC, FerrariAndrea commented on DApp/src/component/DirectoriesCollector.ts
> +        return ris;
The await is on line 87:   `const reader = await this.resolveTD(tds[x]);`

2022-08-25 13:53 UTC, FerrariAndrea commented on DApp/src/component/DirectoriesCollector.ts
> +        return ris;
The await is on line 165: `const tds = await this.getThingFromDir(realDirURL, indexDir, parser);`

2022-08-25 14:05 UTC, FerrariAndrea commented on DApp/src/component/Worker.ts
> +import QueryParser from "./QueryParser";
I think that is an issue of Windows vs Unix file system. It is not the first time that I encounter that...
The problem is that, if I try to push the change of the renamed file from `queryParser` to `QueryParser`, that will not be pushed to github (indeed you can see the file name is still `queryParser` but on my local PC is `QueryParser`.
I use upper case for the first letter of the classes in that repo, so I prefer to have `QueryParser`.
I will try to resolve that issues later, after the marge of all PR, for doing that I'm pretty sure, I need to:

1. remove the file QueryParser, commit and push
2. add QueryParser with the upper case first letter and then commit and push

In my experience that will fix the problem

2022-08-25 14:09 UTC, FerrariAndrea commented on DApp/src/component/Worker.ts
> +              this.cb(computedJsonObj);
That is needed for some tests, I'm not sure I should remove it.
In detail, if we are in a test that is using that worker, the test will set a callback used instead of the function this.err which will cause the `process.exit(1);`.

2022-08-25 14:11 UTC, FerrariAndrea commented on DApp/src/component/consensus/dataCollector.ts
> +    return await recursive();
Yea, that is needed for the logic of the consensus algorithm on data.
You can interpret that like a sampler.

2022-08-25 14:16 UTC, FerrariAndrea commented on DApp/src/component/queryParser.ts
> +var jp = require('jsonpath'); //import jp from "jsonpath"; DO NOT WORK :(
Yes, I tried more than one solution, and `var jp = require('jsonpath');` that work for jest and normal DApp run, `import jp from "jsonpath";` give me error on VSCode and do not work in both.
We can look at that together, and after the PR of issue #10, because in my opinion, that error is related to the TS compiler and the configuration file about it.  In the PR of issue #10, for example, I changed from `node-ts` to `tsc`, that can be might depend on (be influenced by) that too.

2022-08-26 06:11 UTC, FerrariAndrea commented on DApp/src/component/Worker.ts
> +import QueryParser from "./QueryParser";
I confirm the new couple of commit fix that problem

2022-08-26 07:10 UTC, relu91 commented on DApp/src/component/Worker.ts
> +import QueryParser from "./QueryParser";
> I think that is an issue of Windows vs Unix file system. It is not the first time that I encounter that...
The problem is that, if I try to push the change of the renamed file from queryParser to QueryParser, that will not be pushed to github (indeed you can see the file name is still queryParser but on my local PC is QueryParser.
I use upper case for the first letter of the classes in that repo, so I prefer to have QueryParser.

I've not ever experienced such problems with Windows... but I glad that is now solved.

2022-08-26 07:13 UTC, relu91 requested changes
Ok almost ready to merge minor issues below

2022-08-26 07:13 UTC, relu91 commented on DApp/src/component/QueryParser.ts
> +    // }
you forget to remove this

2022-08-26 07:13 UTC, relu91 commented on DApp/src/component/QueryParser.ts
> +        }
and this

2022-08-26 07:13 UTC, relu91 commented on DApp/src/component/QueryParser.ts
> +    // }
and this too

2022-08-26 08:06 UTC, FerrariAndrea commented on DApp/src/component/QueryParser.ts
> +    // }
Yea sorry do not see it (because I remove it and then add it again for fix its name)

2022-08-26 10:49 UTC, relu91 commented
There are some changes in the package.json and package-lock.json that seems related to #10, can you remove unrelated changes?

2022-08-26 12:00 UTC, FerrariAndrea commented
Pls have a look on that, is ok now?

2022-08-26 14:50 UTC, relu91 approved these changes

2022-08-26 14:50 UTC, relu91 commented
Let's move on :)

2022-08-26 14:50 UTC, merged